version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: social-network-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - social-network

  db:
    image: postgres:latest
    container_name: social-network-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - social-network

  nginx:
    image: nginx:alpine
    container_name: social-network-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - social-network

networks:
  social-network:
    driver: bridge

volumes:
  dbdata:
    driver: local 